name: flutter_clean_architecture_boilerplate
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  auto_route: ^9.2.2
  dio: ^5.7.0
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  injectable: ^2.5.0
  logger: ^2.4.0
  alice: ^1.0.0-dev.12
  alice_dio: ^1.0.6
  hive: ^2.2.3
  isar_flutter_libs: ^4.0.0-dev.13
  path_provider: ^2.1.5
  hive_flutter: ^1.1.0
  fpdart: ^1.1.0
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.4.0
  flutter_gen: ^5.7.0
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.13
  dependency_validator: ^3.2.2
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  injectable_generator: ^2.6.2
  intl_utils: ^2.8.7
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true